version: "3"
services:
  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    image: mail
    hostname: ${MX_DOMAIN}
    environment:
      - USERS=${USERS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MX_DOMAIN=${MX_DOMAIN}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - IMAP_DOMAIN=${IMAP_DOMAIN}
      - ADDITIONAL_MAIL_DOMAINS=${ADDITIONAL_MAIL_DOMAINS}
    volumes:
      - ./home:/home/
      - ./letsencrypt:/etc/letsencrypt/
      - letsencrypt-var:/var/lib/letsencrypt/
    networks:
      - mailserver_network
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
      - "4190:4190"
  filter:
    build:
      context: ./filter
      dockerfile: Dockerfile
    image: filter
    hostname: filter.${MAIL_DOMAIN}
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MX_DOMAIN=${MX_DOMAIN}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - IMAP_DOMAIN=${IMAP_DOMAIN}
      - ADDITIONAL_MAIL_DOMAINS=${ADDITIONAL_MAIL_DOMAINS}
    volumes:
      - ./home:/home/
    networks:
      - mailserver_network
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MX_DOMAIN=${MX_DOMAIN}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - IMAP_DOMAIN=${IMAP_DOMAIN}
      - ADDITIONAL_MAIL_DOMAINS=${ADDITIONAL_MAIL_DOMAINS}
    networks:
      - mailserver_network
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - database:/var/www/database/
      - ./letsencrypt:/etc/letsencrypt/
      - letsencrypt-wellknown:/var/www/html/.well-known
      - letsencrypt-var:/var/lib/letsencrypt/
  certbot:
    build: ./certbot
    image: certbot
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MX_DOMAIN=${MX_DOMAIN}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - IMAP_DOMAIN=${IMAP_DOMAIN}
      - ADDITIONAL_MAIL_DOMAINS=${ADDITIONAL_MAIL_DOMAINS}
    volumes:
      - ./letsencrypt:/etc/letsencrypt/
      - letsencrypt-wellknown:/var/www/html/.well-known
      - letsencrypt-var:/var/lib/letsencrypt/
    networks:
      - mailserver_network

networks:
  mailserver_network:
    ipam:
      driver: default
      config:
        - subnet: 172.64.0.0/24
volumes:
  letsencrypt-var:
    driver: local
  letsencrypt-wellknown:
    driver: local
  database:
    driver: local
