version: "3"
services:
  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    image: mail
    environment:
      - USERS=${USERS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_SERVER_DOMAIN=${MAIL_SERVER_DOMAIN}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - IMAP_DOMAIN=${IMAP_DOMAIN}
    volumes:
      - ./home:/home
      - letsencrypt-etc:/etc/letsencrypt/
      - letsencrypt-var:/var/lib/letsencrypt/
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
      - "4190:4190"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web
    environment:
      - USERS=${USERS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_SERVER_DOMAIN=${MAIL_SERVER_DOMAIN}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - IMAP_DOMAIN=${IMAP_DOMAIN}
    ports:
        - "443:443"
    volumes:
      - database:/var/www/database/
      - letsencrypt-etc:/etc/letsencrypt/
      - letsencrypt-var:/var/lib/letsencrypt/
  certbot:
    build: ./certbot
    image: certbot
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_SERVER_DOMAIN=${MAIL_SERVER_DOMAIN}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - IMAP_DOMAIN=${IMAP_DOMAIN}
    volumes:
      - letsencrypt-etc:/etc/letsencrypt/
      - letsencrypt-var:/var/lib/letsencrypt/
    ports:
      - "80:80"
volumes:
  letsencrypt-etc:
    driver: local
  letsencrypt-var:
    driver: local
  database:
    driver: local
