FROM debian:stable
MAINTAINER ago

ENV DEBIAN_FRONTEND noninteractive
ENV TZ Asia/Tokyo

RUN apt-get update \
 && apt-get install -y postfix dovecot-core dovecot-sieve \
 && apt-get clean

COPY ./etc /etc
COPY ./preprocess.sh /
COPY ./entrypoint-postfix.sh /

ENTRYPOINT ["/entrypoint-postfix.sh"]
